"""Generate a Core Flight System (cFS) relative-navigation app whose
GNC step runs the FORMALLY VERIFIED emitted kernels.

The app is written in genuine cFS idiom (CFE_ES_RunLoop main loop,
CFE_SB pipe/subscribe/receive/transmit, EVS events). Its one flight
function — the measurement handler — calls the emitted C directly:
podium_ekf_update_sequential then podium_ekf_predict over a maintained
6-state estimate and 6x6 covariance. Those kernels are EVA-proven
alarm-free and bit-exact-through-CompCert, so the entire arithmetic
path of this flight app is verified.

Full cFE/OSAL is a large external tree, so `generate()` also writes a
MINIMAL portable shim (cfe_shim.h/.c) implementing just the SB/ES/EVS
API the app uses, backed by a stdin/stdout hex-float message
transport. The SAME app source compiles and runs standalone with gcc
against the shim, or drops into a real cFS mission tree unchanged. A
README documents both the cFS and the F-prime (F´) mappings.
"""

from __future__ import annotations

import pathlib

APP_H = r"""/* podium_nav_app.h — generated by podium.emit.cfsapp. DO NOT EDIT.
 * Relative-navigation cFS application: EKF on the verified kernels. */
#ifndef PODIUM_NAV_APP_H
#define PODIUM_NAV_APP_H

#include "cfe_shim.h"

/* Message IDs (mission-assigned in a real deployment) */
#define PODIUM_NAV_MEAS_MID   0x1841  /* in : position measurement   */
#define PODIUM_NAV_STATE_MID  0x0841  /* out: relative state estimate */

/* Software-bus message payloads (packed doubles; a real mission wraps
 * these in CFE_MSG headers, which the shim models). */
typedef struct {
    CFE_MSG_Header_t hdr;
    double pos[3];              /* measured relative position, LVLH [m] */
} PODIUM_NAV_MeasMsg_t;

typedef struct {
    CFE_MSG_Header_t hdr;
    double state[6];           /* estimated (r, v) LVLH */
} PODIUM_NAV_StateMsg_t;

/* App instance data */
typedef struct {
    double x[6];               /* state estimate */
    double P[6][6];            /* covariance */
    double phi[6][6];          /* CW state-transition (const after init) */
    double Q[6][6];            /* process noise (const after init) */
    double r_var;              /* measurement variance */
    CFE_SB_PipeId_t pipe;
    uint32 cycles;
} PODIUM_NAV_App_t;

void PODIUM_NAV_AppMain(void);

#endif
"""

APP_C = r"""/* podium_nav_app.c — generated by podium.emit.cfsapp. DO NOT EDIT.
 *
 * A cFS application. The measurement handler is the ONLY arithmetic and
 * it is entirely emitted, EVA-proven, CompCert-checked C: the flight
 * numerics of this app carry the full podium verification stack. */
#include "podium_nav_app.h"

/* emitted kernels (podium_kernels.c) */
void podium_cw_stm(double n, double t, double out[6][6]);
void podium_ekf_process_noise_wna(double dt, double q_accel,
                                  double out[6][6]);
void podium_ekf_update_sequential(const double x[6], const double p[6][6],
                                  const double z[3], double r_var,
                                  double out0[6], double out1[6][6]);
void podium_ekf_predict(const double x[6], const double p[6][6],
                        const double phi[6][6], const double q[6][6],
                        double out0[6], double out1[6][6]);

static PODIUM_NAV_App_t g;

static void copy6(const double s[6], double d[6]) {
    for (int i = 0; i < 6; i++) d[i] = s[i];
}
static void copy66(const double s[6][6], double d[6][6]) {
    for (int i = 0; i < 6; i++)
        for (int j = 0; j < 6; j++) d[i][j] = s[i][j];
}

/* one measurement cycle: update on the emitted Joseph kernel, then
 * propagate one step — the flight GNC step, in verified C. */
static void PODIUM_NAV_OnMeas(const PODIUM_NAV_MeasMsg_t *m) {
    double x1[6], P1[6][6];
    podium_ekf_update_sequential(g.x, g.P, m->pos, g.r_var, x1, P1);
    copy6(x1, g.x);
    copy66(P1, g.P);
    podium_ekf_predict(g.x, g.P, g.phi, g.Q, x1, P1);
    copy6(x1, g.x);
    copy66(P1, g.P);
    g.cycles++;

    PODIUM_NAV_StateMsg_t out;
    CFE_MSG_Init(&out.hdr, PODIUM_NAV_STATE_MID, sizeof out);
    copy6(g.x, out.state);
    CFE_SB_TransmitMsg(&out.hdr, true);
}

static void PODIUM_NAV_Init(void) {
    /* 400 km circular reference; docking-grade measurement noise. */
    const double n = 0.0011313666536110223, dt = 1.0;
    for (int i = 0; i < 6; i++) {
        g.x[i] = 0.0;
        for (int j = 0; j < 6; j++) g.P[i][j] = 0.0;
    }
    for (int i = 0; i < 3; i++) g.P[i][i] = 100.0 * 100.0;
    for (int i = 3; i < 6; i++) g.P[i][i] = 1.0;
    podium_cw_stm(n, dt, g.phi);
    podium_ekf_process_noise_wna(dt, 2.0e-6, g.Q);
    /* r_var sits at the EVA-proven envelope floor (0.01 = (10 cm)^2):
     * the app runs a configuration the sound-value gate certifies
     * overflow-free, not an arbitrary tuning. */
    g.r_var = 0.01;
    g.cycles = 0;

    CFE_SB_CreatePipe(&g.pipe, 16, "PODIUM_NAV_PIPE");
    CFE_SB_Subscribe(PODIUM_NAV_MEAS_MID, g.pipe);
    CFE_EVS_SendEvent(1, CFE_EVS_INFORMATION,
                      "PODIUM_NAV initialized (verified-kernel EKF)");
}

void PODIUM_NAV_AppMain(void) {
    CFE_ES_PerfLogEntry(0);
    PODIUM_NAV_Init();

    /* standard cFS run loop: block on the SB, dispatch by MsgId. */
    while (CFE_ES_RunLoop()) {
        CFE_SB_Buffer_t *buf = 0;
        int32 st = CFE_SB_ReceiveBuffer(&buf, g.pipe, CFE_SB_PEND_FOREVER);
        if (st != CFE_SUCCESS || buf == 0) break;
        CFE_SB_MsgId_t mid;
        CFE_MSG_GetMsgId(&mid, &buf->msg);
        if (mid == PODIUM_NAV_MEAS_MID)
            PODIUM_NAV_OnMeas((const PODIUM_NAV_MeasMsg_t *)buf);
    }
    CFE_ES_PerfLogExit(0);
}

/* Standalone entry (shim build). In a real mission cFE calls
 * PODIUM_NAV_AppMain via the ES app table; here main() drives it. */
int main(void) {
    PODIUM_NAV_AppMain();
    return 0;
}
"""

SHIM_H = r"""/* cfe_shim.h — generated by podium.emit.cfsapp. DO NOT EDIT.
 *
 * A MINIMAL, portable stand-in for the cFE Software Bus / Executive
 * Services / Event Services API, sufficient to compile and run a cFS
 * app standalone against a stdin/stdout message transport. It is NOT
 * cFE — it exists so the generated app source (which IS cFS idiom)
 * can be exercised without the full OSAL/cFE tree. Swap this header
 * for the real cfe.h in a mission build and the app is unchanged. */
#ifndef CFE_SHIM_H
#define CFE_SHIM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef int32_t  int32;
typedef uint32_t uint32;
typedef uint16_t uint16;

#define CFE_SUCCESS 0
#define CFE_SB_PEND_FOREVER (-1)
#define CFE_EVS_INFORMATION 1
#define CFE_EVS_ERROR 2

typedef uint16 CFE_SB_MsgId_t;
typedef int    CFE_SB_PipeId_t;

typedef struct { CFE_SB_MsgId_t mid; uint16 length; } CFE_MSG_Header_t;
typedef struct { CFE_MSG_Header_t msg; } CFE_SB_Buffer_t;

void  CFE_MSG_Init(CFE_MSG_Header_t *h, CFE_SB_MsgId_t mid, size_t len);
void  CFE_MSG_GetMsgId(CFE_SB_MsgId_t *mid, const CFE_MSG_Header_t *h);
int32 CFE_SB_CreatePipe(CFE_SB_PipeId_t *p, uint16 depth, const char *name);
int32 CFE_SB_Subscribe(CFE_SB_MsgId_t mid, CFE_SB_PipeId_t p);
int32 CFE_SB_ReceiveBuffer(CFE_SB_Buffer_t **buf, CFE_SB_PipeId_t p,
                           int32 timeout);
int32 CFE_SB_TransmitMsg(CFE_MSG_Header_t *h, bool inc);
int   CFE_ES_RunLoop(void);
void  CFE_ES_PerfLogEntry(uint32 id);
void  CFE_ES_PerfLogExit(uint32 id);
void  CFE_EVS_SendEvent(uint16 id, uint16 type, const char *msg);

#endif
"""

SHIM_C = r"""/* cfe_shim.c — generated by podium.emit.cfsapp. DO NOT EDIT.
 *
 * Backs the shim SB with a line transport: each stdin line is a hex-
 * float measurement triple delivered as a PODIUM_NAV MEAS message;
 * every transmitted STATE message is printed as 6 hex floats. This is
 * the same %a transport the golden-vector tests use, so the app's
 * output is directly comparable to the Python EKF reference. */
#include "podium_nav_app.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void CFE_MSG_Init(CFE_MSG_Header_t *h, CFE_SB_MsgId_t mid, size_t len) {
    h->mid = mid; h->length = (uint16)len;
}
void CFE_MSG_GetMsgId(CFE_SB_MsgId_t *mid, const CFE_MSG_Header_t *h) {
    *mid = h->mid;
}
int32 CFE_SB_CreatePipe(CFE_SB_PipeId_t *p, uint16 depth, const char *name) {
    (void)depth; (void)name; *p = 1; return CFE_SUCCESS;
}
int32 CFE_SB_Subscribe(CFE_SB_MsgId_t mid, CFE_SB_PipeId_t p) {
    (void)mid; (void)p; return CFE_SUCCESS;
}

/* one static inbound buffer, refilled from stdin on each receive */
static PODIUM_NAV_MeasMsg_t g_in;

int32 CFE_SB_ReceiveBuffer(CFE_SB_Buffer_t **buf, CFE_SB_PipeId_t p,
                           int32 timeout) {
    (void)p; (void)timeout;
    char line[256];
    if (!fgets(line, sizeof line, stdin)) return -1;  /* end of stream */
    double a, b, c;
    char *t = strtok(line, " \n");
    if (!t) return -1;
    a = strtod(t, 0);
    b = strtod(strtok(0, " \n"), 0);
    c = strtod(strtok(0, " \n"), 0);
    CFE_MSG_Init(&g_in.hdr, PODIUM_NAV_MEAS_MID, sizeof g_in);
    g_in.pos[0] = a; g_in.pos[1] = b; g_in.pos[2] = c;
    *buf = (CFE_SB_Buffer_t *)&g_in;
    return CFE_SUCCESS;
}

int32 CFE_SB_TransmitMsg(CFE_MSG_Header_t *h, bool inc) {
    (void)inc;
    const PODIUM_NAV_StateMsg_t *m = (const PODIUM_NAV_StateMsg_t *)h;
    for (int i = 0; i < 6; i++)
        printf(i ? " %a" : "%a", m->state[i]);
    printf("\n");
    return CFE_SUCCESS;
}

/* run until the transport is drained (ReceiveBuffer returns end) */
int  CFE_ES_RunLoop(void) { return !feof(stdin); }
void CFE_ES_PerfLogEntry(uint32 id) { (void)id; }
void CFE_ES_PerfLogExit(uint32 id) { (void)id; }
void CFE_EVS_SendEvent(uint16 id, uint16 type, const char *msg) {
    (void)id; (void)type; fprintf(stderr, "[EVS] %s\n", msg);
}
"""

README = r"""# podium_nav_app — a cFS relative-navigation app on verified kernels

Generated by `podium.emit.cfsapp`. This is a Core Flight System (cFS)
application whose GNC arithmetic is **entirely emitted, EVA-proven,
CompCert-checked C**: the measurement handler calls
`podium_ekf_update_sequential` then `podium_ekf_predict` over a
maintained 6-state estimate and 6x6 covariance.

## Files

- `podium_nav_app.c/.h` — the app, in genuine cFS idiom.
- `cfe_shim.c/.h` — a minimal, portable stand-in for the cFE SB/ES/EVS
  API so the app compiles and runs standalone (no OSAL/full cFE). It is
  NOT cFE; swap it for the real `cfe.h` in a mission build unchanged.
- `podium_kernels.c` — the emitted flight kernels (copied in by the
  generator).

## Build & run standalone

    gcc -std=c99 -O2 -ffp-contract=off \
        podium_nav_app.c cfe_shim.c podium_kernels.c -lm -o nav_app
    ./nav_app < measurements.txt   # each line: 3 hex-float positions

Every transmitted STATE message prints as 6 hex floats — the same `%a`
transport the golden-vector tests use, so the output is directly
comparable to the Python EKF.

## Mapping to a real cFS mission

| this example                     | real cFS                          |
| -------------------------------- | --------------------------------- |
| `PODIUM_NAV_AppMain`             | app entry in the ES app table     |
| `cfe_shim.h`                     | `cfe.h` (SB/ES/EVS/MSG)           |
| `CFE_SB_CreatePipe/Subscribe`    | identical                         |
| `CFE_SB_ReceiveBuffer` loop      | identical (`CFE_ES_RunLoop`)      |
| `PODIUM_NAV_*_MID`               | mission-assigned message IDs      |
| `cfe_shim.c` line transport      | the real Software Bus             |

## Mapping to F´ (F Prime)

| this example                     | F´                                |
| -------------------------------- | --------------------------------- |
| `PODIUM_NAV_App_t`               | a `Component`                     |
| MEAS subscription                | an input (async) `port`           |
| `PODIUM_NAV_OnMeas` handler      | the port handler                  |
| STATE transmit                   | an output `port` / telemetry chan |
| init constants (phi, Q, r_var)   | `parameters`                      |
| (add) reset/init command         | a `command`                       |

The verified kernels are the same in both; only the bus glue differs.
"""


def generate(outdir: str, kernels_c: str) -> None:
    """Write the cFS app tree (app, shim, kernels, README) to outdir."""
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "podium_nav_app.h").write_text(APP_H)
    (out / "podium_nav_app.c").write_text(APP_C)
    (out / "cfe_shim.h").write_text(SHIM_H)
    (out / "cfe_shim.c").write_text(SHIM_C)
    (out / "podium_kernels.c").write_text(kernels_c)
    (out / "README.md").write_text(README)
