"""EVA driver generation: the sound-value-gate harness.

For each emitted kernel, the driver constructs every input from an
interval — the declared @contract interval where one exists, otherwise
a DOCUMENTED operating range from `DEFAULT_RANGES` — using Frama-C's
`Frama_C_double_interval`, then calls the kernel. Running EVA over the
result proves (sound float-interval semantics, not testing) that no
division by zero, overflow to infinity, or invalid access occurs for
ANY input in those ranges.

Honesty rule encoded here: every entry in DEFAULT_RANGES is a range the
driver ASSUMES beyond a declared contract — each is a contract gap that
should eventually move into the kernel's @contract. The generator
writes that list into the driver header so the gap is visible in the
artifact itself.
"""

from __future__ import annotations

from typing import Callable

from podium.emit import cemit

# operating ranges assumed where kernels lack @contract intervals
# (name, param) -> (lo, hi); arrays get the range element-wise
DEFAULT_RANGES: dict[tuple[str, str], tuple[float, float]] = {
    ("normalize", "q"): (-2.0, 2.0),
    ("multiply", "a"): (-1.5, 1.5),
    ("multiply", "b"): (-1.5, 1.5),
    ("conjugate", "q"): (-1.5, 1.5),
    ("rotate", "q"): (-1.5, 1.5),
    ("rotate", "v"): (-1e3, 1e3),
    ("deriv", "q"): (-1.5, 1.5),
    ("deriv", "w_body"): (-1.0, 1.0),
    ("error", "q"): (-1.5, 1.5),
    ("error", "q_ref"): (-1.5, 1.5),
    ("mean_motion", "mu"): (3.0e14, 4.5e14),
    ("mean_motion", "a"): (6.5e6, 4.3e7),
    ("cw_deriv", "x"): (-1e5, 1e5),
    ("cw_deriv", "n"): (1e-5, 1e-2),
    ("cw_deriv", "u"): (-1.0, 1.0),
    ("stm", "n"): (1e-5, 1e-2),
    ("stm", "t"): (0.0, 1e5),
    ("kepler_eccentric", "mean_anom"): (-3.15, 3.15),
    ("kepler_eccentric", "e"): (0.0, 0.9),
    ("true_from_eccentric", "ecc_anom"): (-3.15, 3.15),
    ("true_from_eccentric", "e"): (0.0, 0.9),
    ("eccentric_from_true", "theta"): (-3.15, 3.15),
    ("eccentric_from_true", "e"): (0.0, 0.9),
    ("propagate_true_anomaly", "n"): (1e-5, 1e-2),
    ("propagate_true_anomaly", "e"): (0.0, 0.9),
    ("propagate_true_anomaly", "theta0"): (-3.15, 3.15),
    ("propagate_true_anomaly", "dt"): (0.0, 1e5),
    ("stm_keplerian", "dt"): (0.0, 1e5),
    ("map_roe_to_lvlh", "roe"): (-1e-2, 1e-2),
    ("map_roe_to_lvlh", "a"): (6.5e6, 4.3e7),
    ("map_roe_to_lvlh", "u"): (-7.0, 7.0),
    ("map_lvlh_to_roe", "x"): (-1e5, 1e5),
    ("map_lvlh_to_roe", "a"): (6.5e6, 4.3e7),
    ("map_lvlh_to_roe", "u"): (-7.0, 7.0),
    ("control_matrix", "a"): (6.5e6, 4.3e7),
    ("control_matrix", "u"): (-7.0, 7.0),
}


def emit_eva_driver(funcs: "list[Callable[..., object]]") -> str:
    """The EVA entry point calling every kernel on interval inputs."""
    metas, _nodes = cemit.analyze_all(funcs)
    lines = ["/* EVA driver — generated by podium.emit.evagen. Inputs are",
             "   contract intervals where declared; entries below marked",
             "   ASSUMED are operating ranges pending contract coverage. */",
             '#include "__fc_builtin.h"', ""]
    for meta in metas.values():
        lines.append(cemit._signature(meta) + ";")
    lines.append("")
    assumed = []
    blocks = []
    for f in funcs:
        meta = metas[f.__name__]
        name = meta.py_name
        body = [f"static void check_{name}(void) {{"]
        args = []
        for p in meta.param_order:
            iv = meta.contracts.get(p)
            if iv is not None:
                lo, hi = float(iv.lo), float(iv.hi)
            else:
                key = (name, p)
                if key not in DEFAULT_RANGES:
                    raise cemit.EmitError(f"no range for {name}.{p}")
                lo, hi = DEFAULT_RANGES[key]
                assumed.append(f"{name}.{p} in [{lo!r}, {hi!r}]")
            if p in meta.param_arrays:
                nlen = meta.param_arrays[p]
                body.append(f"    double {p}[{nlen}];")
                body.append(f"    for (int i = 0; i < {nlen}; i++)"
                            f" {p}[i] = Frama_C_double_interval"
                            f"({lo!r}, {hi!r});")
            else:
                body.append(f"    double {p} = Frama_C_double_interval"
                            f"({lo!r}, {hi!r});")
            args.append(p)
        if meta.out_shape is not None:
            dims = "".join(f"[{d}]" for d in meta.out_shape)
            body.append(f"    double out{dims};")
            args.append("out")
            body.append(f"    {meta.c_name}({', '.join(args)});")
        else:
            body.append(f"    double r = {meta.c_name}({', '.join(args)});")
            body.append("    (void)r;")
        body.append("}")
        blocks.append("\n".join(body))
    lines.append("/* ASSUMED (contract gaps): "
                 + ("; ".join(assumed) if assumed else "none") + " */")
    lines.append("")
    lines.extend(blocks)
    lines.append("")
    lines.append("void eva_main(void) {")
    for f in funcs:
        lines.append(f"    check_{f.__name__}();")
    lines.append("}")
    return "\n".join(lines)
