/* cfe_shim.c — generated by podium.emit.cfsapp. DO NOT EDIT.
 *
 * Backs the shim SB with a line transport: each stdin line is a hex-
 * float measurement triple delivered as a PODIUM_NAV MEAS message;
 * every transmitted STATE message is printed as 6 hex floats. This is
 * the same %a transport the golden-vector tests use, so the app's
 * output is directly comparable to the Python EKF reference. */
#include "podium_nav_app.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void CFE_MSG_Init(CFE_MSG_Header_t *h, CFE_SB_MsgId_t mid, size_t len) {
    h->mid = mid; h->length = (uint16)len;
}
void CFE_MSG_GetMsgId(CFE_SB_MsgId_t *mid, const CFE_MSG_Header_t *h) {
    *mid = h->mid;
}
int32 CFE_SB_CreatePipe(CFE_SB_PipeId_t *p, uint16 depth, const char *name) {
    (void)depth; (void)name; *p = 1; return CFE_SUCCESS;
}
int32 CFE_SB_Subscribe(CFE_SB_MsgId_t mid, CFE_SB_PipeId_t p) {
    (void)mid; (void)p; return CFE_SUCCESS;
}

/* one static inbound buffer, refilled from stdin on each receive */
static PODIUM_NAV_MeasMsg_t g_in;

int32 CFE_SB_ReceiveBuffer(CFE_SB_Buffer_t **buf, CFE_SB_PipeId_t p,
                           int32 timeout) {
    (void)p; (void)timeout;
    char line[256];
    if (!fgets(line, sizeof line, stdin)) return -1;  /* end of stream */
    double a, b, c;
    char *t = strtok(line, " \n");
    if (!t) return -1;
    a = strtod(t, 0);
    b = strtod(strtok(0, " \n"), 0);
    c = strtod(strtok(0, " \n"), 0);
    CFE_MSG_Init(&g_in.hdr, PODIUM_NAV_MEAS_MID, sizeof g_in);
    g_in.pos[0] = a; g_in.pos[1] = b; g_in.pos[2] = c;
    *buf = (CFE_SB_Buffer_t *)&g_in;
    return CFE_SUCCESS;
}

int32 CFE_SB_TransmitMsg(CFE_MSG_Header_t *h, bool inc) {
    (void)inc;
    const PODIUM_NAV_StateMsg_t *m = (const PODIUM_NAV_StateMsg_t *)h;
    for (int i = 0; i < 6; i++)
        printf(i ? " %a" : "%a", m->state[i]);
    printf("\n");
    return CFE_SUCCESS;
}

/* run until the transport is drained (ReceiveBuffer returns end) */
int  CFE_ES_RunLoop(void) { return !feof(stdin); }
void CFE_ES_PerfLogEntry(uint32 id) { (void)id; }
void CFE_ES_PerfLogExit(uint32 id) { (void)id; }
void CFE_EVS_SendEvent(uint16 id, uint16 type, const char *msg) {
    (void)id; (void)type; fprintf(stderr, "[EVS] %s\n", msg);
}
