/* cfe_shim.h — generated by podium.emit.cfsapp. DO NOT EDIT.
 *
 * A MINIMAL, portable stand-in for the cFE Software Bus / Executive
 * Services / Event Services API, sufficient to compile and run a cFS
 * app standalone against a stdin/stdout message transport. It is NOT
 * cFE — it exists so the generated app source (which IS cFS idiom)
 * can be exercised without the full OSAL/cFE tree. Swap this header
 * for the real cfe.h in a mission build and the app is unchanged. */
#ifndef CFE_SHIM_H
#define CFE_SHIM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef int32_t  int32;
typedef uint32_t uint32;
typedef uint16_t uint16;

#define CFE_SUCCESS 0
#define CFE_SB_PEND_FOREVER (-1)
#define CFE_EVS_INFORMATION 1
#define CFE_EVS_ERROR 2

typedef uint16 CFE_SB_MsgId_t;
typedef int    CFE_SB_PipeId_t;

typedef struct { CFE_SB_MsgId_t mid; uint16 length; } CFE_MSG_Header_t;
typedef struct { CFE_MSG_Header_t msg; } CFE_SB_Buffer_t;

void  CFE_MSG_Init(CFE_MSG_Header_t *h, CFE_SB_MsgId_t mid, size_t len);
void  CFE_MSG_GetMsgId(CFE_SB_MsgId_t *mid, const CFE_MSG_Header_t *h);
int32 CFE_SB_CreatePipe(CFE_SB_PipeId_t *p, uint16 depth, const char *name);
int32 CFE_SB_Subscribe(CFE_SB_MsgId_t mid, CFE_SB_PipeId_t p);
int32 CFE_SB_ReceiveBuffer(CFE_SB_Buffer_t **buf, CFE_SB_PipeId_t p,
                           int32 timeout);
int32 CFE_SB_TransmitMsg(CFE_MSG_Header_t *h, bool inc);
int   CFE_ES_RunLoop(void);
void  CFE_ES_PerfLogEntry(uint32 id);
void  CFE_ES_PerfLogExit(uint32 id);
void  CFE_EVS_SendEvent(uint16 id, uint16 type, const char *msg);

#endif
