/* podium_nav_app.h — generated by podium.emit.cfsapp. DO NOT EDIT.
 * Relative-navigation cFS application: EKF on the verified kernels. */
#ifndef PODIUM_NAV_APP_H
#define PODIUM_NAV_APP_H

#include "cfe_shim.h"

/* Message IDs (mission-assigned in a real deployment) */
#define PODIUM_NAV_MEAS_MID   0x1841  /* in : position measurement   */
#define PODIUM_NAV_STATE_MID  0x0841  /* out: relative state estimate */

/* Software-bus message payloads (packed doubles; a real mission wraps
 * these in CFE_MSG headers, which the shim models). */
typedef struct {
    CFE_MSG_Header_t hdr;
    double pos[3];              /* measured relative position, LVLH [m] */
} PODIUM_NAV_MeasMsg_t;

typedef struct {
    CFE_MSG_Header_t hdr;
    double state[6];           /* estimated (r, v) LVLH */
} PODIUM_NAV_StateMsg_t;

/* App instance data */
typedef struct {
    double x[6];               /* state estimate */
    double P[6][6];            /* covariance */
    double phi[6][6];          /* CW state-transition (const after init) */
    double Q[6][6];            /* process noise (const after init) */
    double r_var;              /* measurement variance */
    CFE_SB_PipeId_t pipe;
    uint32 cycles;
} PODIUM_NAV_App_t;

void PODIUM_NAV_AppMain(void);

#endif
