/* podium_nav_app.c — generated by podium.emit.cfsapp. DO NOT EDIT.
 *
 * A cFS application. The measurement handler is the ONLY arithmetic and
 * it is entirely emitted, EVA-proven, CompCert-checked C: the flight
 * numerics of this app carry the full podium verification stack. */
#include "podium_nav_app.h"

/* emitted kernels (podium_kernels.c) */
void podium_cw_stm(double n, double t, double out[6][6]);
void podium_ekf_process_noise_wna(double dt, double q_accel,
                                  double out[6][6]);
void podium_ekf_update_sequential(const double x[6], const double p[6][6],
                                  const double z[3], double r_var,
                                  double out0[6], double out1[6][6]);
void podium_ekf_predict(const double x[6], const double p[6][6],
                        const double phi[6][6], const double q[6][6],
                        double out0[6], double out1[6][6]);

static PODIUM_NAV_App_t g;

static void copy6(const double s[6], double d[6]) {
    for (int i = 0; i < 6; i++) d[i] = s[i];
}
static void copy66(const double s[6][6], double d[6][6]) {
    for (int i = 0; i < 6; i++)
        for (int j = 0; j < 6; j++) d[i][j] = s[i][j];
}

/* one measurement cycle: update on the emitted Joseph kernel, then
 * propagate one step — the flight GNC step, in verified C. */
static void PODIUM_NAV_OnMeas(const PODIUM_NAV_MeasMsg_t *m) {
    double x1[6], P1[6][6];
    podium_ekf_update_sequential(g.x, g.P, m->pos, g.r_var, x1, P1);
    copy6(x1, g.x);
    copy66(P1, g.P);
    podium_ekf_predict(g.x, g.P, g.phi, g.Q, x1, P1);
    copy6(x1, g.x);
    copy66(P1, g.P);
    g.cycles++;

    PODIUM_NAV_StateMsg_t out;
    CFE_MSG_Init(&out.hdr, PODIUM_NAV_STATE_MID, sizeof out);
    copy6(g.x, out.state);
    CFE_SB_TransmitMsg(&out.hdr, true);
}

static void PODIUM_NAV_Init(void) {
    /* 400 km circular reference; docking-grade measurement noise. */
    const double n = 0.0011313666536110223, dt = 1.0;
    for (int i = 0; i < 6; i++) {
        g.x[i] = 0.0;
        for (int j = 0; j < 6; j++) g.P[i][j] = 0.0;
    }
    for (int i = 0; i < 3; i++) g.P[i][i] = 100.0 * 100.0;
    for (int i = 3; i < 6; i++) g.P[i][i] = 1.0;
    podium_cw_stm(n, dt, g.phi);
    podium_ekf_process_noise_wna(dt, 2.0e-6, g.Q);
    /* r_var sits at the EVA-proven envelope floor (0.01 = (10 cm)^2):
     * the app runs a configuration the sound-value gate certifies
     * overflow-free, not an arbitrary tuning. */
    g.r_var = 0.01;
    g.cycles = 0;

    CFE_SB_CreatePipe(&g.pipe, 16, "PODIUM_NAV_PIPE");
    CFE_SB_Subscribe(PODIUM_NAV_MEAS_MID, g.pipe);
    CFE_EVS_SendEvent(1, CFE_EVS_INFORMATION,
                      "PODIUM_NAV initialized (verified-kernel EKF)");
}

void PODIUM_NAV_AppMain(void) {
    CFE_ES_PerfLogEntry(0);
    PODIUM_NAV_Init();

    /* standard cFS run loop: block on the SB, dispatch by MsgId. */
    while (CFE_ES_RunLoop()) {
        CFE_SB_Buffer_t *buf = 0;
        int32 st = CFE_SB_ReceiveBuffer(&buf, g.pipe, CFE_SB_PEND_FOREVER);
        if (st != CFE_SUCCESS || buf == 0) break;
        CFE_SB_MsgId_t mid;
        CFE_MSG_GetMsgId(&mid, &buf->msg);
        if (mid == PODIUM_NAV_MEAS_MID)
            PODIUM_NAV_OnMeas((const PODIUM_NAV_MeasMsg_t *)buf);
    }
    CFE_ES_PerfLogExit(0);
}

/* Standalone entry (shim build). In a real mission cFE calls
 * PODIUM_NAV_AppMain via the ES app table; here main() drives it. */
int main(void) {
    PODIUM_NAV_AppMain();
    return 0;
}
