/* podium_kernels — generated by podium.emit.cemit; DO NOT EDIT.
   Compile: gcc -std=c99 -O2 -ffp-contract=off (SSE2/binary64);
   bit-exactness vs CPython depends on those flags. */
#include <math.h>

void podium_quat_normalize(const double q[4], double out[4]);
void podium_quat_multiply(const double a[4], const double b[4], double out[4]);
void podium_quat_conjugate(const double q[4], double out[4]);
void podium_quat_rotate(const double q[4], const double v[3], double out[3]);
void podium_quat_deriv(const double q[4], const double w_body[3], double out[4]);
void podium_quat_error(const double q[4], const double q_ref[4], double out[3]);
double podium_cw_mean_motion(double mu, double a);
void podium_cw_cw_deriv(const double x[6], double n, const double u[3], double out[6]);
void podium_cw_stm(double n, double t, double out[6][6]);
double podium_ya_kepler_eccentric(double mean_anom, double e);
double podium_ya_true_from_eccentric(double ecc_anom, double e);
double podium_ya_eccentric_from_true(double theta, double e);
double podium_ya_propagate_true_anomaly(double n, double e, double theta0, double dt);
void podium_roe_stm_keplerian(double n, double dt, double out[6][6]);
void podium_roe_map_roe_to_lvlh(const double roe[6], double a, double n, double u, double out[6]);
void podium_roe_map_lvlh_to_roe(const double x[6], double a, double n, double u, double out[6]);
void podium_roe_control_matrix(double a, double n, double u, double out[6][3]);
void podium_ekf_predict(const double x[6], const double p[6][6], const double phi[6][6], const double q[6][6], double out0[6], double out1[6][6]);
void podium_ekf_update_sequential(const double x[6], const double p[6][6], const double z[3], double r_var, double out0[6], double out1[6][6]);
void podium_ekf_process_noise_wna(double dt, double q_accel, double out[6][6]);

void podium_quat_normalize(const double q[4], double out[4]) {
    double n2 = ((((q[0] * q[0]) + (q[1] * q[1])) + (q[2] * q[2])) + (q[3] * q[3]));
    if (n2 > 1e-300) {
        double inv = (1.0 / sqrt(n2));
        out[0] = (q[0] * inv);
        out[1] = (q[1] * inv);
        out[2] = (q[2] * inv);
        out[3] = (q[3] * inv);
    } else {
        out[0] = 1.0;
        out[1] = 0.0;
        out[2] = 0.0;
        out[3] = 0.0;
    }
    return;
}

void podium_quat_multiply(const double a[4], const double b[4], double out[4]) {
    out[0] = ((((a[0] * b[0]) - (a[1] * b[1])) - (a[2] * b[2])) - (a[3] * b[3]));
    out[1] = ((((a[0] * b[1]) + (a[1] * b[0])) + (a[2] * b[3])) - (a[3] * b[2]));
    out[2] = ((((a[0] * b[2]) - (a[1] * b[3])) + (a[2] * b[0])) + (a[3] * b[1]));
    out[3] = ((((a[0] * b[3]) + (a[1] * b[2])) - (a[2] * b[1])) + (a[3] * b[0]));
    return;
}

void podium_quat_conjugate(const double q[4], double out[4]) {
    out[0] = q[0];
    out[1] = (-q[1]);
    out[2] = (-q[2]);
    out[3] = (-q[3]);
    return;
}

void podium_quat_rotate(const double q[4], const double v[3], double out[3]) {
    double tx = (2.0 * ((q[2] * v[2]) - (q[3] * v[1])));
    double ty = (2.0 * ((q[3] * v[0]) - (q[1] * v[2])));
    double tz = (2.0 * ((q[1] * v[1]) - (q[2] * v[0])));
    out[0] = ((v[0] + (q[0] * tx)) + ((q[2] * tz) - (q[3] * ty)));
    out[1] = ((v[1] + (q[0] * ty)) + ((q[3] * tx) - (q[1] * tz)));
    out[2] = ((v[2] + (q[0] * tz)) + ((q[1] * ty) - (q[2] * tx)));
    return;
}

void podium_quat_deriv(const double q[4], const double w_body[3], double out[4]) {
    out[0] = (0.5 * ((((-q[1]) * w_body[0]) - (q[2] * w_body[1])) - (q[3] * w_body[2])));
    out[1] = (0.5 * (((q[0] * w_body[0]) + (q[2] * w_body[2])) - (q[3] * w_body[1])));
    out[2] = (0.5 * (((q[0] * w_body[1]) - (q[1] * w_body[2])) + (q[3] * w_body[0])));
    out[3] = (0.5 * (((q[0] * w_body[2]) + (q[1] * w_body[1])) - (q[2] * w_body[0])));
    return;
}

void podium_quat_error(const double q[4], const double q_ref[4], double out[3]) {
    double _t0[4];
    podium_quat_conjugate(q_ref, _t0);
    double dq[4];
    podium_quat_multiply(_t0, q, dq);
    double sign = ((dq[0] >= 0.0) ? 1.0 : (-1.0));
    out[0] = ((2.0 * sign) * dq[1]);
    out[1] = ((2.0 * sign) * dq[2]);
    out[2] = ((2.0 * sign) * dq[3]);
    return;
}

double podium_cw_mean_motion(double mu, double a) {
    return sqrt((mu / ((a * a) * a)));
}

void podium_cw_cw_deriv(const double x[6], double n, const double u[3], double out[6]) {
    out[0] = x[3];
    out[1] = x[4];
    out[2] = x[5];
    out[3] = (((((3.0 * n) * n) * x[0]) + ((2.0 * n) * x[4])) + u[0]);
    out[4] = ((((-2.0) * n) * x[3]) + u[1]);
    out[5] = ((((-n) * n) * x[2]) + u[2]);
    return;
}

void podium_cw_stm(double n, double t, double out[6][6]) {
    double s = sin((n * t));
    double c = cos((n * t));
    for (int _i = 0; _i < 36; _i++) ((double *)out)[_i] = 0.0;
    out[0][0] = (4.0 - (3.0 * c));
    out[0][3] = (s / n);
    out[0][4] = ((2.0 * (1.0 - c)) / n);
    out[1][0] = (6.0 * (s - (n * t)));
    out[1][1] = 1.0;
    out[1][3] = ((2.0 * (c - 1.0)) / n);
    out[1][4] = (((4.0 * s) - ((3.0 * n) * t)) / n);
    out[2][2] = c;
    out[2][5] = (s / n);
    out[3][0] = ((3.0 * n) * s);
    out[3][3] = c;
    out[3][4] = (2.0 * s);
    out[4][0] = ((6.0 * n) * (c - 1.0));
    out[4][3] = ((-2.0) * s);
    out[4][4] = ((4.0 * c) - 3.0);
    out[5][2] = ((-n) * s);
    out[5][5] = c;
    return;
}

double podium_ya_kepler_eccentric(double mean_anom, double e) {
    double ecc = (mean_anom + (e * sin(mean_anom)));
    for (int _ = 0; _ < 20; _++) {
        double f = ((ecc - (e * sin(ecc))) - mean_anom);
        double fp = (1.0 - (e * cos(ecc)));
        ecc = (ecc - (f / fp));
    }
    return ecc;
}

double podium_ya_true_from_eccentric(double ecc_anom, double e) {
    return (2.0 * atan2((sqrt((1.0 + e)) * sin((0.5 * ecc_anom))), (sqrt((1.0 - e)) * cos((0.5 * ecc_anom)))));
}

double podium_ya_eccentric_from_true(double theta, double e) {
    return (2.0 * atan2((sqrt((1.0 - e)) * sin((0.5 * theta))), (sqrt((1.0 + e)) * cos((0.5 * theta)))));
}

double podium_ya_propagate_true_anomaly(double n, double e, double theta0, double dt) {
    double ecc0 = podium_ya_eccentric_from_true(theta0, e);
    double mean0 = (ecc0 - (e * sin(ecc0)));
    double mean1 = fmod((mean0 + (n * dt)), 6.283185307179586);
    if (mean1 < 0.0) {
        mean1 += 6.283185307179586;
    }
    double ecc1 = podium_ya_kepler_eccentric(mean1, e);
    double theta1 = podium_ya_true_from_eccentric(ecc1, e);
    if (theta1 < 0.0) {
        theta1 += 6.283185307179586;
    }
    return theta1;
}

/*@
  requires 0x1.4f8b588e368f1p-17 <= n <= 0x1.47ae147ae147bp-7;
*/
/* [spec] { [in, range(1e-05,0.01)] n; } */
void podium_roe_stm_keplerian(double n, double dt, double out[6][6]) {
    for (int _i = 0; _i < 36; _i++) ((double *)out)[_i] = 0.0;
    for (int _i = 0; _i < 6; _i++) out[_i][_i] = 1.0;
    out[1][0] = (((-1.5) * n) * dt);
    return;
}

/*@
  requires 0x1.4f8b588e368f1p-17 <= n <= 0x1.47ae147ae147bp-7;
*/
/* [spec] { [in, range(1e-05,0.01)] n; } */
void podium_roe_map_roe_to_lvlh(const double roe[6], double a, double n, double u, double out[6]) {
    double su = sin(u);
    double cu = cos(u);
    out[0] = (a * ((roe[0] - (roe[2] * cu)) - (roe[3] * su)));
    out[1] = (a * ((roe[1] + ((2.0 * roe[2]) * su)) - ((2.0 * roe[3]) * cu)));
    out[2] = (a * ((roe[4] * su) - (roe[5] * cu)));
    out[3] = ((a * n) * ((roe[2] * su) - (roe[3] * cu)));
    out[4] = ((a * n) * ((((-1.5) * roe[0]) + ((2.0 * roe[2]) * cu)) + ((2.0 * roe[3]) * su)));
    out[5] = ((a * n) * ((roe[4] * cu) + (roe[5] * su)));
    return;
}

/*@
  requires 0x1.4f8b588e368f1p-17 <= n <= 0x1.47ae147ae147bp-7;
*/
/* [spec] { [in, range(1e-05,0.01)] n; } */
void podium_roe_map_lvlh_to_roe(const double x[6], double a, double n, double u, double out[6]) {
    double su = sin(u);
    double cu = cos(u);
    double xa = (x[0] / a);
    double ya = (x[1] / a);
    double za = (x[2] / a);
    double vxa = (x[3] / (a * n));
    double vya = (x[4] / (a * n));
    double vza = (x[5] / (a * n));
    out[0] = ((4.0 * xa) + (2.0 * vya));
    out[1] = (ya - (2.0 * vxa));
    double c1 = (out[0] - xa);
    out[2] = ((c1 * cu) + (vxa * su));
    out[3] = ((c1 * su) - (vxa * cu));
    out[4] = ((za * su) + (vza * cu));
    out[5] = (((-za) * cu) + (vza * su));
    return;
}

/*@
  requires 0x1.4f8b588e368f1p-17 <= n <= 0x1.47ae147ae147bp-7;
*/
/* [spec] { [in, range(1e-05,0.01)] n; } */
void podium_roe_control_matrix(double a, double n, double u, double out[6][3]) {
    double su = sin(u);
    double cu = cos(u);
    for (int _i = 0; _i < 18; _i++) ((double *)out)[_i] = 0.0;
    double s = (1.0 / (n * a));
    out[0][1] = (2.0 * s);
    out[1][0] = ((-2.0) * s);
    out[2][0] = (su * s);
    out[2][1] = ((2.0 * cu) * s);
    out[3][0] = ((-cu) * s);
    out[3][1] = ((2.0 * su) * s);
    out[4][2] = (cu * s);
    out[5][2] = (su * s);
    return;
}

void podium_ekf_predict(const double x[6], const double p[6][6], const double phi[6][6], const double q[6][6], double out0[6], double out1[6][6]) {
    for (int _i1 = 0; _i1 < 6; _i1++) {
        double _acc = 0.0;
        for (int _i3 = 0; _i3 < 6; _i3++) _acc += phi[_i1][_i3] * x[_i3];
        out0[_i1] = _acc;
    }
    double p_prop[6][6];
    double _a0[6][6];
    double _a1[6][6];
    for (int _i6 = 0; _i6 < 6; _i6++) for (int _i7 = 0; _i7 < 6; _i7++) {
        double _acc = 0.0;
        for (int _i8 = 0; _i8 < 6; _i8++) _acc += phi[_i6][_i8] * p[_i8][_i7];
        _a1[_i6][_i7] = _acc;
    }
    for (int _i9 = 0; _i9 < 6; _i9++) for (int _i10 = 0; _i10 < 6; _i10++) {
        double _acc = 0.0;
        for (int _i11 = 0; _i11 < 6; _i11++) _acc += _a1[_i9][_i11] * phi[_i10][_i11];
        _a0[_i9][_i10] = _acc;
    }
    for (int _i4 = 0; _i4 < 6; _i4++) for (int _i5 = 0; _i5 < 6; _i5++)
        p_prop[_i4][_i5] = _a0[_i4][_i5] + q[_i4][_i5];
    double _a2[6][6];
    for (int _i14 = 0; _i14 < 6; _i14++) for (int _i15 = 0; _i15 < 6; _i15++)
        _a2[_i14][_i15] = p_prop[_i14][_i15] + p_prop[_i15][_i14];
    for (int _i12 = 0; _i12 < 6; _i12++) for (int _i13 = 0; _i13 < 6; _i13++)
        out1[_i12][_i13] = 0.5 * _a2[_i12][_i13];
    return;
}

/*@
  requires 0x1.47ae147ae147bp-7 <= r_var <= 0x1.e848000000000p+19;
*/
/* [spec] { [in, range(0.01,1000000.0)] r_var; } */
void podium_ekf_update_sequential(const double x[6], const double p[6][6], const double z[3], double r_var, double out0[6], double out1[6][6]) {
    for (int i = 0; i < 6; i++) {
        out0[i] = x[i];
        for (int j = 0; j < 6; j++) {
            out1[i][j] = p[i][j];
        }
    }
    double pn[6][6];
    double kk[6];
    for (int m = 0; m < 3; m++) {
        double s = (out1[m][m] + r_var);
        if (s < r_var) {
            s = r_var;
        }
        for (int i = 0; i < 6; i++) {
            kk[i] = (out1[i][m] / s);
        }
        double nu = (z[m] - out0[m]);
        for (int i = 0; i < 6; i++) {
            out0[i] = (out0[i] + (kk[i] * nu));
        }
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 6; j++) {
                pn[i][j] = ((((out1[i][j] - (kk[i] * out1[m][j])) - (out1[i][m] * kk[j])) + ((kk[i] * out1[m][m]) * kk[j])) + ((r_var * kk[i]) * kk[j]));
            }
        }
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 6; j++) {
                out1[i][j] = (0.5 * (pn[i][j] + pn[j][i]));
            }
        }
    }
    return;
}

/*@
  requires 0x1.0624dd2f1a9fcp-10 <= dt <= 0x1.2c00000000000p+9;
  requires 0x0.0p+0 <= q_accel <= 0x1.0000000000000p+0;
*/
/* [spec] { [in, range(0.001,600.0)] dt; [in, range(0.0,1.0)] q_accel; } */
void podium_ekf_process_noise_wna(double dt, double q_accel, double out[6][6]) {
    for (int _i = 0; _i < 36; _i++) ((double *)out)[_i] = 0.0;
    double q_pp = ((((q_accel * dt) * dt) * dt) / 3.0);
    double q_pv = (((q_accel * dt) * dt) / 2.0);
    double q_vv = (q_accel * dt);
    for (int i = 0; i < 3; i++) {
        out[i][i] = q_pp;
        out[i][i + 3] = q_pv;
        out[i + 3][i] = q_pv;
        out[i + 3][i + 3] = q_vv;
    }
    return;
}
