#!/usr/bin/env python3
"""The sound value gate: Frama-C/EVA over the emitted kernels.

Emits the C for every translated kernel plus the interval-input driver
(podium.emit.evagen), runs EVA in the official framac/frama-c container
(Ubuntu 22.04 ships no frama-c package), and FAILS unless the analysis
reports zero alarms — a sound float-interval proof that no division by
zero, overflow to infinity, or invalid access occurs for ANY input in
the contracted/stated ranges.

Usage:  python3 tools/eva_gate.py [workdir]
Exit 0 = proven alarm-free; nonzero otherwise. Prints the EVA summary.
"""

import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from podium.emit import cemit, evagen  # noqa: E402
from podium.emit.kernels import FLIGHT_KERNELS as KERNELS  # noqa: E402

IMAGE = "framac/frama-c:dev"


def main() -> int:
    work = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else \
        pathlib.Path("tmp/rw/eva")
    work.mkdir(parents=True, exist_ok=True)
    (work / "kernels.c").write_text(cemit.emit_module(KERNELS))
    (work / "eva_driver.c").write_text(evagen.emit_eva_driver(KERNELS))

    cmd = [
        "docker", "run", "--rm",
        "-v", f"{work.resolve()}:/work", "-w", "/work",
        IMAGE, "frama-c", "-eva", "-main", "eva_main",
        "-eva-precision", "2", "-eva-no-alloc-returns-null",
        "kernels.c", "eva_driver.c",
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, check=False)
    out = r.stdout + r.stderr
    (work / "eva_report.txt").write_text(out)
    m = re.search(r"(\d+) alarms? generated by the analysis", out)
    tail = "\n".join(out.splitlines()[-25:])
    print(tail)
    if r.returncode != 0 and m is None:
        print("EVA GATE: analysis failed to run")
        return 2
    if m is None:
        print("EVA GATE: could not find alarm summary")
        return 2
    alarms = int(m.group(1))
    if alarms == 0:
        print("EVA GATE: PROVEN alarm-free over the stated input ranges")
        return 0
    print(f"EVA GATE: {alarms} alarms — see {work}/eva_report.txt")
    return 1


if __name__ == "__main__":
    sys.exit(main())
